server:
  port: 8080  # Tomcat default port


spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092


    gazeEvents-topic: gazeEvents-topic
    clickEvents-topic: clickEvents-topic